apiVersion: v1
kind: Service

metadata:
  name: btcd

spec:
  type: ClusterIP
  ports:
  - name: btcd-network
    port: 8333
    targetPort: btcd-network
    protocol: TCP
  selector:
    app: btcd

---

apiVersion: v1
kind: Service

metadata:
  name: btcd-external

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: btcd-rpc
    port: 8334
    targetPort: btcd-rpc
    protocol: TCP
  selector:
    app: btcd
