apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: btc
nameSuffix: -latest

labels:
  - includeSelectors: true
    pairs:
      instance: latest

resources:
  - ../../base

images:
  - name: code.liv.io/liv/bitcoin-core
    newTag: 31.1-1

patches:
  - patch: |-
      - op: add
        path: /spec/externalIPs
        value:
          - 10.1.13.221
    target:
      kind: Service
      name: int
  - patch: |-
      - op: add
        path: /spec/externalIPs
        value:
          - 10.1.13.221
    target:
      kind: Service
      name: ext
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ADDNODE
          value: "10.1.13.222:8333 10.1.13.223:8333"
    target:
      kind: Deployment
      name: btc
